name: healthcheck
defaults:
  run:
    shell: bash
        
on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: openhackuc9203t8userprofile
  AZURE_WEBAPP_SLOT: staging
  AZURE_WEBAPP_URL: https://openhackuc9203t8userprofile.azurewebsites.net/
  AZURE_WEBAPP_STAGING_URL: https://openhackuc9203t8userprofile-staging.azurewebsites.net/
  HEALTH_CHECK_URL: https://openhackuc9203t8userprofile-staging.azurewebsites.net/api/healthcheck/userprofile

jobs:
  run-staging-healthcheck:
    runs-on: ubuntu-latest
    # needs: docker-build-push
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: poll-app-health
      working-directory: ./scripts
      run: |
        chmod +x ./healthcheck.sh
        ./healthcheck.sh -i ${{ env.HEALTH_CHECK_URL }}

