name: healthcheck
defaults:
  run:
    shell: bash
        
on:
  workflow_dispatch:
env:
  AZURE_RG: openhackuc9203t8rg
  AZURE_WEBAPP_NAME: openhackuc9203t8userprofile
  AZURE_WEBAPP_SLOT: staging
  AZURE_WEBAPP_URL: https://openhackuc9203t8userprofile.azurewebsites.net/
  AZURE_WEBAPP_STAGING_URL: https://openhackuc9203t8userprofile-staging.azurewebsites.net/

jobs:

  validate_staging_and_swap_prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # needs: deploy_staging
    steps:
    - name: curl
      id: poi-health-check
      uses: satak/webrequest-action@master
      with:
        url: ${{env.AZURE_WEBAPP_STAGING_URL}}/api/healthcheck/poi
        method: GET
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Check Output Swap Slots
      shell: pwsh
      run: |
        $output = '${{ steps.poi-health-check.outputs.output }}' | ConvertFrom-Json
        Write-Host " Status code is $($output.statusCode) "
        if($($output.statusCode) -eq 200) {
        Write-host "Healthy"
        az webapp deployment slot swap --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RG }} --slot staging --target-slot production
        }
        else {
        Write-Error "POI API is not healthy"
        }