on: 
  push:
    branches:
      - master
  workflow_dispatch:

name: AzureLoginSample
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}