name: Trips Build

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - 'apis/trips/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'apis/trips/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/charleswm/devops-openhack-team6

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build apis/trips -v .
      env:
        GOPATH: /home/runner/work/devops-openhack-team6/go
