name: Trips Build

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - 'apis/trips/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'apis/trips/**'
env:
  AZURE_WEBAPP_NAME: openhackuc9203t8trips
  AZURE_WEBAPP_SLOT: staging

jobs:
  # build:

  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./apis/trips

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Setup Go
  #     uses: actions/setup-go@v2

  #   - name: Get dependencies
  #     run: |
  #       go get
  #       if [ -f Gopkg.toml ]; then
  #           curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  #           dep ensure
  #       fi

  #   - name: Build
  #     run: go build -v .

  docker-build-push:  
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackuc9203t8acr.azurecr.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build ./apis/trips/ -t openhackuc9203t8acr.azurecr.io/devopsoh/api-trips:${{github.run_number}}
    - name: Docker push
      run: docker push openhackuc9203t8acr.azurecr.io/devopsoh/api-trips:${{github.run_number}}
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TRIPS_STAGING  }} # Define secret variable in repository settings as per action documentation
        slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
        images: openhackuc9203t8acr.azurecr.io/devopsoh/api-trips:${{github.run_number}}
