# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: userprofile build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./apis/userprofile
    - run: npm run build --if-present
      working-directory: ./apis/userprofile
#    - run: npm test

  docker-build-push:  
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackuc9203t8acr.azurecr.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build ./apis/userprofile/ -t openhackuc9203t8acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}}
    - name: Docker push
      run: docker push openhackuc9203t8acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}}
