# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: User build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'apis/user-java/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/user-java/**'
env:
  AZURE_WEBAPP_NAME: openhackuc9203t8userjava
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/user-java

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build user-java
      run: mvn -B package --file pom.xml
  
  docker-build-push:  
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackuc9203t8acr.azurecr.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build ./apis/user-java/ -t openhackuc9203t8acr.azurecr.io/devopsoh/api-user-java:${{github.run_number}}
    - name: Docker push
      run: docker push openhackuc9203t8acr.azurecr.io/devopsoh/api-user-java:${{github.run_number}}
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_USERJAVA  }} # Define secret variable in repository settings as per action documentation
        images: openhackuc9203t8acr.azurecr.io/devopsoh/api-user-java:${{github.run_number}}
