# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: userprofile build
defaults:
  run:
    shell: bash
        
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'
env:
  AZURE_RG: openhackuc9203t8rg
  AZURE_WEBAPP_NAME: openhackuc9203t8userprofile
  AZURE_WEBAPP_SLOT: staging
  AZURE_WEBAPP_URL: https://openhackuc9203t8userprofile.azurewebsites.net/
  AZURE_WEBAPP_STAGING_URL: https://openhackuc9203t8userprofile-staging.azurewebsites.net/
  HEALTH_CHECK_URL: https://openhackuc9203t8userprofile-staging.azurewebsites.net/api/healthcheck/userprofile

jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#       working-directory: ./apis/userprofile
#     - run: npm run build --if-present
#       working-directory: ./apis/userprofile
# #    - run: npm test

  docker-build-push:  
    runs-on: ubuntu-latest
#     needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackuc9203t8acr.azurecr.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build ./apis/userprofile/ -t openhackuc9203t8acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}}
    - name: Docker push
      run: docker push openhackuc9203t8acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_USERPROFILE_STAGING  }} # Define secret variable in repository settings as per action documentation
        slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
        images: openhackuc9203t8acr.azurecr.io/devopsoh/api-userprofile:${{github.run_number}}
  
  # run-staging-healthcheck:
  #   runs-on: ubuntu-latest
  #   needs: docker-build-push
  #   steps:
  #   - name: poll-app-health
  #     run: ./healthcheck.sh -i ${{ env.HEALTH_CHECK_URL }}
  swap:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps: 
      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: swaparoo
        run: az webapp deployment slot swap  -g ${{ env.AZURE_RG }} -n ${{ env.AZURE_WEBAPP_NAME }} --slot staging --target-slot production